import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "1rem",
      screens: { "2xl": "430px" },
    },
    extend: {
      fontFamily: {
        heading: ["Fredoka", "sans-serif"],
        body: ["Nunito", "sans-serif"],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
          light: "hsl(var(--primary-light))",
          dark: "hsl(var(--primary-dark))",
          pale: "hsl(var(--primary-pale))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
          dark: "hsl(var(--secondary-dark))",
          light: "hsl(var(--secondary-light))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          dark: "hsl(var(--destructive-dark))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        game: {
          green: {
            dark: "hsl(var(--green-dark))",
            mid: "hsl(var(--green-mid))",
            light: "hsl(var(--green-light))",
            pale: "hsl(var(--green-pale))",
          },
          gold: {
            DEFAULT: "hsl(var(--gold))",
            dark: "hsl(var(--gold-dark))",
            light: "hsl(var(--gold-light))",
          },
          brown: {
            DEFAULT: "hsl(var(--brown))",
            dark: "hsl(var(--brown-dark))",
            light: "hsl(var(--brown-light))",
          },
          red: "hsl(var(--farm-red))",
          blue: "hsl(var(--farm-blue))",
          sky: "hsl(var(--farm-sky))",
        },
        boss: {
          dark: "hsl(var(--boss-dark))",
          mid: "hsl(var(--boss-mid))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 4px)",
        sm: "calc(var(--radius) - 8px)",
        xl: "24px",
        "2xl": "32px",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "plant-sway": {
          "0%, 100%": { transform: "rotate(-1deg)" },
          "50%": { transform: "rotate(1deg)" },
        },
        "float-up": {
          "0%": { opacity: "1", transform: "translateY(0)" },
          "100%": { opacity: "0", transform: "translateY(-60px)" },
        },
        "cloud-drift": {
          "0%": { transform: "translateX(-60px)" },
          "100%": { transform: "translateX(420px)" },
        },
        "splash-progress": {
          "0%": { width: "0%" },
          "60%": { width: "70%" },
          "100%": { width: "100%" },
        },
        "splash-in": {
          "0%": { transform: "scale(0.7)", opacity: "0" },
          "100%": { transform: "scale(1)", opacity: "1" },
        },
        "logo-pulse": {
          "0%, 100%": { transform: "scale(1)" },
          "50%": { transform: "scale(1.05)" },
        },
        "float-leaf": {
          "0%, 100%": { transform: "translateY(0) rotate(0deg)" },
          "50%": { transform: "translateY(-15px) rotate(10deg)" },
        },
        "slide-up": {
          "0%": { transform: "translateY(100%)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
        "fade-in-up": {
          "0%": { transform: "translateY(10px)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
        "boss-idle": {
          "0%, 100%": { transform: "translateY(0) scale(1)" },
          "50%": { transform: "translateY(-8px) scale(1.02)" },
        },
        "damage-float": {
          "0%": { transform: "translateY(0)", opacity: "1" },
          "100%": { transform: "translateY(-40px)", opacity: "0" },
        },
        "event-pulse": {
          "0%, 100%": { boxShadow: "0 0 0 0 rgba(231,76,60,0.3)" },
          "50%": { boxShadow: "0 0 0 6px rgba(231,76,60,0)" },
        },
        "sun-pulse": {
          "0%, 100%": { transform: "scale(1)", opacity: "0.9" },
          "50%": { transform: "scale(1.1)", opacity: "1" },
        },
        "sparkle-up": {
          "0%": { transform: "translateY(0) scale(1)", opacity: "1" },
          "100%": { transform: "translateY(-30px) scale(0.3)", opacity: "0" },
        },
        "ult-glow": {
          "0%, 100%": { boxShadow: "0 4px 15px rgba(108,92,231,0.4)" },
          "50%": { boxShadow: "0 4px 25px rgba(108,92,231,0.7)" },
        },
        "gem-pop": {
          "0%": { transform: "scale(1)" },
          "50%": { transform: "scale(1.3)" },
          "100%": { transform: "scale(0)", opacity: "0" },
        },
        "bug-wiggle": {
          "0%, 100%": { transform: "rotate(-8deg) scale(1)" },
          "25%": { transform: "rotate(8deg) scale(1.1)" },
          "50%": { transform: "rotate(-5deg) scale(0.95)" },
          "75%": { transform: "rotate(6deg) scale(1.05)" },
        },
        "rain-drop": {
          "0%": { transform: "translateY(-20px)", opacity: "0" },
          "10%": { opacity: "1" },
          "100%": { transform: "translateY(100vh)", opacity: "0.3" },
        },
        "snow-fall": {
          "0%": { transform: "translateY(-10px) translateX(0) rotate(0deg)", opacity: "0" },
          "10%": { opacity: "1" },
          "100%": { transform: "translateY(100vh) translateX(30px) rotate(360deg)", opacity: "0.2" },
        },
        "storm-flash": {
          "0%, 94%, 100%": { opacity: "0" },
          "95%": { opacity: "0.6" },
          "96%": { opacity: "0" },
          "97%": { opacity: "0.3" },
        },
        "wind-blow": {
          "0%": { transform: "translateX(-100px)", opacity: "0" },
          "20%": { opacity: "1" },
          "100%": { transform: "translateX(500px)", opacity: "0" },
        },
        "heat-shimmer": {
          "0%, 100%": { opacity: "0.3" },
          "50%": { opacity: "0.6" },
        },
        "screen-shake": {
          "0%, 100%": { transform: "translateX(0)" },
          "10%": { transform: "translateX(-6px)" },
          "20%": { transform: "translateX(6px)" },
          "30%": { transform: "translateX(-4px)" },
          "40%": { transform: "translateX(4px)" },
          "50%": { transform: "translateX(-2px)" },
          "60%": { transform: "translateX(0)" },
        },
        "scale-in": {
          "0%": { transform: "scale(0.5)", opacity: "0" },
          "100%": { transform: "scale(1)", opacity: "1" },
        },
        "fade-in": {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        "combo-burst": {
          "0%": { transform: "translateX(-50%) scale(0.3)", opacity: "0" },
          "50%": { transform: "translateX(-50%) scale(1.2)", opacity: "1" },
          "100%": { transform: "translateX(-50%) scale(1)", opacity: "1" },
        },
        "boss-attack": {
          "0%": { transform: "translateY(0) scale(1)" },
          "15%": { transform: "translateY(-20px) scale(1.15)" },
          "30%": { transform: "translateY(10px) scale(1.2)" },
          "50%": { transform: "translateY(-5px) scale(1.1)" },
          "100%": { transform: "translateY(0) scale(1)" },
        },
        "boss-atk-flash": {
          "0%": { background: "transparent" },
          "15%": { background: "rgba(231,76,60,0.25)" },
          "30%": { background: "transparent" },
          "45%": { background: "rgba(231,76,60,0.15)" },
          "60%": { background: "transparent" },
          "100%": { background: "transparent" },
        },
        "ult-flash": {
          "0%": { background: "rgba(108,92,231,0.4)" },
          "25%": { background: "rgba(224,86,253,0.3)" },
          "50%": { background: "rgba(108,92,231,0.5)" },
          "75%": { background: "rgba(162,155,254,0.2)" },
          "100%": { background: "rgba(108,92,231,0.1)" },
        },
        "dodge-pulse": {
          "0%, 100%": { transform: "scale(1.1)", boxShadow: "0 0 15px rgba(243,156,18,0.5)" },
          "50%": { transform: "scale(1.2)", boxShadow: "0 0 30px rgba(243,156,18,0.8)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "plant-sway": "plant-sway 4s ease-in-out infinite",
        "float-up": "float-up 1.2s ease-out forwards",
        "cloud-drift": "cloud-drift 25s linear infinite",
        "splash-progress": "splash-progress 2.5s ease-in-out forwards",
        "splash-in": "splash-in 1s ease-out",
        "logo-pulse": "logo-pulse 2s ease-in-out infinite",
        "float-leaf": "float-leaf 6s ease-in-out infinite",
        "slide-up": "slide-up 0.4s ease-out",
        "fade-in-up": "fade-in-up 0.4s ease-out both",
        "boss-idle": "boss-idle 2s ease-in-out infinite",
        "damage-float": "damage-float 1.5s ease-out infinite",
        "event-pulse": "event-pulse 2s ease-in-out infinite",
        "sun-pulse": "sun-pulse 3s ease-in-out infinite",
        "sparkle-up": "sparkle-up 1s ease-out forwards",
        "ult-glow": "ult-glow 1.5s ease-in-out infinite",
        "gem-pop": "gem-pop 0.3s ease-out forwards",
        "bug-wiggle": "bug-wiggle 0.5s ease-in-out infinite",
        "rain-drop": "rain-drop 1s linear infinite",
        "snow-fall": "snow-fall 5s linear infinite",
        "storm-flash": "storm-flash 4s ease-in-out infinite",
        "wind-blow": "wind-blow 2s linear infinite",
        "heat-shimmer": "heat-shimmer 3s ease-in-out infinite",
        "screen-shake": "screen-shake 0.5s ease-out",
        "scale-in": "scale-in 0.3s ease-out",
        "fade-in": "fade-in 0.3s ease-out",
        "combo-burst": "combo-burst 0.4s cubic-bezier(0.34, 1.56, 0.64, 1)",
        "boss-attack": "boss-attack 0.6s ease-out",
        "boss-atk-flash": "boss-atk-flash 0.8s ease-out",
        "ult-flash": "ult-flash 1.5s ease-out",
        "dodge-pulse": "dodge-pulse 0.4s ease-in-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
